-- Primary Keys
ALTER TABLE Employee
ADD CONSTRAINT PK_Employee PRIMARY KEY (EmployeeID);

ALTER TABLE [User]
ADD CONSTRAINT PK_User PRIMARY KEY (UserID);

ALTER TABLE Client
ADD CONSTRAINT PK_Client PRIMARY KEY (ClientID);

ALTER TABLE Sale
ADD CONSTRAINT PK_Sale PRIMARY KEY (SaleID);

ALTER TABLE SaleDetail
ADD CONSTRAINT PK_SaleDetail PRIMARY KEY (SaleDetailID);

ALTER TABLE Product
ADD CONSTRAINT PK_Product PRIMARY KEY (ProductID);

ALTER TABLE Category
ADD CONSTRAINT PK_Category PRIMARY KEY (CategoryID);

-- Foreign Keys
ALTER TABLE [User]
ADD CONSTRAINT FK_User_Employee FOREIGN KEY (EmployeeID)
REFERENCES Employee(EmployeeID);

ALTER TABLE Sale
ADD CONSTRAINT FK_Sale_User FOREIGN KEY (UserID)
REFERENCES [User](UserID);

ALTER TABLE Sale
ADD CONSTRAINT FK_Sale_Client FOREIGN KEY (ClientID)
REFERENCES Client(ClientID);

ALTER TABLE SaleDetail
ADD CONSTRAINT FK_SaleDetail_Sale FOREIGN KEY (SaleID)
REFERENCES Sale(SaleID);

ALTER TABLE SaleDetail
ADD CONSTRAINT FK_SaleDetail_Product FOREIGN KEY (ProductID)
REFERENCES Product(ProductID);

ALTER TABLE Product
ADD CONSTRAINT FK_Product_Category FOREIGN KEY (CategoryID)
REFERENCES Category(CategoryID);
